### PR TITLE
Add rfinder

### PR DESCRIPTION
**Pull request by eakadams**
A script for producing RFInder plots for fluxcal.

Placed where report tool can find them in an extremely hacky way.

### CODE REVIEW

**Comment by tammojan** [comment]
It would be good (and not too hard) to replace the system call to a python by a call to the rfinder class.

**Comment by eakadams** [comment]
Not too hard for you and not too hard for me are two different things ;). I'll see if I have time to get to it tonight, otherwise will merge this version so other people can at least run it for their QA.

**Comment by tammojan** [comment]
Sounds good, this can also be changed later!

**Comment by tammojan** [comment]
You accidentally pulled in Björn's commit (#35) into this branch as well. We can fix that, or just merge this PR and delete the other one.

**Comment by tammojan** [comment]
To use the rfinder as a python thing, `import rfinder` and then change the os.system lines with this one (sorry, not tested..):
```
    # Following lines borrowed from rfinder main script
    RFInder = rfinder.rfinder()
    rfi_par = RFInder.main("-idir {datapath:s} -i {msfile:s} -tel apertif -mode use_flags -odir {qapath:s} -fl 0 -tStep 5 -yesClp".format(datapath=datapath, ms  file=msfile, qapath=qapath).split(" "))
    rfi_par.go(rfi_par.cfg_par)
```

**Comment by eakadams** [comment]
Unfortunately I got an error when trying that way:
```(pipeline) adams@happili-01:~$ python /home/adams/dataqa/run_rfinder.py 190326001 3C147
root - INFO : Logging started!
root - INFO : To see the log in a bash window use the following command:
root - INFO : tail -n +1 -f /data/apertif/190326001/qa/preflag/run_rfinder.log
log-rfinder.log - WARNING : ------ Reading default parameter file in your directory ------

log-rfinder.log - WARNING : ------ Updating arguments given from terminal ------

log-rfinder.log - WARNING : ------ STARTING RFI analysis ------

Traceback (most recent call last):
  File "/home/adams/dataqa/run_rfinder.py", line 67, in <module>
    rfi_par.go(rfi_par.cfg_par)
  File "/home/apercal/RFInder/rfinder/__init__.py", line 370, in go
    if self.cfg_par[task]['rfi_enable']==True:
KeyError: 'rfi_enable'
```

Looks like I would have to dig into the parameter file more to understand what's happening. I'm going to merge what's there for now and pick this up later.

**Pull request merged**
